name: Classic-Build

on:
  release:
    types: [ published ]

jobs:

  build-classic:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: BigWigsMods/packager@master
        name: Build Classic and upload to CurseForge
        with:
          args: -l -g classic

      - name: Post changelog
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "** New Classic release ${{ env.RELEASE_VERSION }} pushed to CurseForge see https://www.curseforge.com/wow/addons/elvui-spellranks**"

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}


  build-bc:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: BigWigsMods/packager@master
        name: Build Classic and upload to CurseForge
        with:
          args: -l -g bcc

      - name: Post changelog
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "** New BC release ${{ env.RELEASE_VERSION }} pushed to CurseForge see https://www.curseforge.com/wow/addons/elvui-spellranks**"

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}